# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-priority', 'todo_list']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='Empty', max_length=500),
        ),
    ]
