# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_item_completion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='todo_list',
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['completion_date', '-priority', 'title']},
        ),
        migrations.AddField(
            model_name='list',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='list',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(default='----'),
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Urgent')], default=2),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
