# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160902_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='completion_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 8, 22, 32, 933559)),
        ),
    ]
