# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 08:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20160902_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['completiondate', '-priority', 'title']},
        ),
        migrations.RenameField(
            model_name='list',
            old_name='created_date',
            new_name='createddate',
        ),
        migrations.RemoveField(
            model_name='list',
            name='completion_date',
        ),
        migrations.AddField(
            model_name='list',
            name='completiondate',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 3, 8, 24, 2, 2226)),
        ),
    ]
